import WasmGemmGnaf.Wasm.Core.ReadCompleteArrays
import WasmGemmGnaf.Wasm.Core.ReadCompleteBytes
import WasmGemmGnaf.Wasm.Core.ReadCompleteLoads
import WasmGemmGnaf.Wasm.Core.ReadCompleteMemory
import WasmGemmGnaf.Wasm.Core.ReadCompleteStructural
import WasmGemmGnaf.Wasm.Core.ReadCompleteTables

set_option autoImplicit false
set_option maxHeartbeats 4000000
set_option maxRecDepth 10000

namespace WasmGemmGnaf.Wasm.Core.Exec

theorem step_readA_mem_completeReadSuccessorsOf {fuel : Nat}
    {z : State} (complete : RefMatchCompleteAt fuel z)
    {rule : ReadRule} {is is' : List AdminInstr}
    (h : Step_readA z rule is is') :
    (.read rule (sourcePlains is), (z, is')) ∈
      completeReadSuccessorsOf fuel (z, is) complete := by
  cases h
  case block => exact block_mem_completeReadSuccessorsOf complete (by apply Step_read.block (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case loop => exact loop_mem_completeReadSuccessorsOf complete (by apply Step_read.loop (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case brOnCastSucceed => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (brOnCastSucceed_mem_readSuccessorsOf complete (by apply Step_read.brOnCastSucceed (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case brOnCastFail => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (brOnCastFail_mem_readSuccessorsOf complete (by apply Step_read.brOnCastFail (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case brOnCastFailSucceed => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (brOnCastFailSucceed_mem_readSuccessorsOf complete (by apply Step_read.brOnCastFailSucceed (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case brOnCastFailFail => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (brOnCastFailFail_mem_readSuccessorsOf complete (by apply Step_read.brOnCastFailFail (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case call => exact call_mem_completeReadSuccessorsOf complete (by apply Step_read.call (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case callRefNull => exact callRefNull_mem_completeReadSuccessorsOf complete (by apply Step_read.callRefNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case callRefFunc => exact callRefFunc_mem_completeReadSuccessorsOf complete (by apply Step_read.callRefFunc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case returnCall => exact returnCall_mem_completeReadSuccessorsOf complete (by apply Step_read.returnCall (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case returnCallRefLabel => exact returnCallRefLabel_mem_completeReadSuccessorsOf complete (by apply Step_read.returnCallRefLabel (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case returnCallRefHandler => exact returnCallRefHandler_mem_completeReadSuccessorsOf complete (by apply Step_read.returnCallRefHandler (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case returnCallRefFrameNull => exact returnCallRefFrameNull_mem_completeReadSuccessorsOf complete (by apply Step_read.returnCallRefFrameNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case returnCallRefFrameAddr => exact returnCallRefFrameAddr_mem_completeReadSuccessorsOf complete (by apply Step_read.returnCallRefFrameAddr (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefNull => exact throwRefNull_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefInstrs => exact throwRefInstrs_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefInstrs (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefLabel => exact throwRefLabel_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefLabel (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefFrame => exact throwRefFrame_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefFrame (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefHandlerEmpty => exact throwRefHandlerEmpty_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefHandlerEmpty (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefHandlerCatch => exact throwRefHandlerCatch_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefHandlerCatch (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefHandlerCatchRef => exact throwRefHandlerCatchRef_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefHandlerCatchRef (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefHandlerCatchAll => exact throwRefHandlerCatchAll_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefHandlerCatchAll (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefHandlerCatchAllRef => exact throwRefHandlerCatchAllRef_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefHandlerCatchAllRef (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case throwRefHandlerNext => exact throwRefHandlerNext_mem_completeReadSuccessorsOf complete (by apply Step_read.throwRefHandlerNext (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tryTable => exact tryTable_mem_completeReadSuccessorsOf complete (by apply Step_read.tryTable (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case localGet => exact localGet_mem_completeReadSuccessorsOf complete (by apply Step_read.localGet (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case globalGet => exact globalGet_mem_completeReadSuccessorsOf complete (by apply Step_read.globalGet (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableGetOob => exact tableGetOob_mem_completeReadSuccessorsOf complete (by apply Step_read.tableGetOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableGetVal => exact tableGetVal_mem_completeReadSuccessorsOf complete (by apply Step_read.tableGetVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableSize => exact tableSize_mem_completeReadSuccessorsOf complete (by apply Step_read.tableSize (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableFillOob => exact tableFillOob_mem_completeReadSuccessorsOf complete (by apply Step_read.tableFillOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableFillZero => exact tableFillZero_mem_completeReadSuccessorsOf complete (by apply Step_read.tableFillZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableFillSucc => exact tableFillSucc_mem_completeReadSuccessorsOf complete (by apply Step_read.tableFillSucc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableCopyOob => exact tableCopyOob_mem_completeReadSuccessorsOf complete (by apply Step_read.tableCopyOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableCopyZero => exact tableCopyZero_mem_completeReadSuccessorsOf complete (by apply Step_read.tableCopyZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableCopyLe => exact tableCopyLe_mem_completeReadSuccessorsOf complete (by apply Step_read.tableCopyLe (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableCopyGt => exact tableCopyGt_mem_completeReadSuccessorsOf complete (by apply Step_read.tableCopyGt (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableInitOob => exact tableInitOob_mem_completeReadSuccessorsOf complete (by apply Step_read.tableInitOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableInitZero => exact tableInitZero_mem_completeReadSuccessorsOf complete (by apply Step_read.tableInitZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case tableInitSucc => exact tableInitSucc_mem_completeReadSuccessorsOf complete (by apply Step_read.tableInitSucc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case loadNumOob => exact loadNumOob_mem_completeReadSuccessorsOf complete (by apply Step_read.loadNumOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case loadNumVal => exact loadNumVal_mem_completeReadSuccessorsOf complete (by apply Step_read.loadNumVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case loadPackOob => exact loadPackOob_mem_completeReadSuccessorsOf complete (by apply Step_read.loadPackOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case loadPackVal => exact loadPackVal_mem_completeReadSuccessorsOf complete (by apply Step_read.loadPackVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadOob => exact vloadOob_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadVal => exact vloadVal_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadPackOob => exact vloadPackOob_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadPackOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadPackVal => exact vloadPackVal_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadPackVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadSplatOob => exact vloadSplatOob_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadSplatOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadSplatVal => exact vloadSplatVal_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadSplatVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadZeroOob => exact vloadZeroOob_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadZeroOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadZeroVal => exact vloadZeroVal_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadZeroVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadLaneOob => exact vloadLaneOob_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadLaneOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case vloadLaneVal => exact vloadLaneVal_mem_completeReadSuccessorsOf complete (by apply Step_read.vloadLaneVal (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memorySize => exact memorySize_mem_completeReadSuccessorsOf complete (by apply Step_read.memorySize (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryFillOob => exact memoryFillOob_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryFillOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryFillZero => exact memoryFillZero_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryFillZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryFillSucc => exact memoryFillSucc_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryFillSucc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryCopyOob => exact memoryCopyOob_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryCopyOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryCopyZero => exact memoryCopyZero_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryCopyZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryCopyLe => exact memoryCopyLe_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryCopyLe (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryCopyGt => exact memoryCopyGt_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryCopyGt (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryInitOob => exact memoryInitOob_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryInitOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryInitZero => exact memoryInitZero_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryInitZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case memoryInitSucc => exact memoryInitSucc_mem_completeReadSuccessorsOf complete (by apply Step_read.memoryInitSucc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case refNullIdx => exact refNullIdx_mem_completeReadSuccessorsOf complete (by apply Step_read.refNullIdx (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case refFunc => exact refFunc_mem_completeReadSuccessorsOf complete (by apply Step_read.refFunc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case refTestTrue => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (refTestTrue_mem_readSuccessorsOf complete (by apply Step_read.refTestTrue (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case refTestFalse => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (refTestFalse_mem_readSuccessorsOf complete (by apply Step_read.refTestFalse (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case refCastSucceed => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (refCastSucceed_mem_readSuccessorsOf complete (by apply Step_read.refCastSucceed (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case refCastFail => exact mem_completeReadSuccessorsOf_of_mem_readSuccessorsOf complete (refCastFail_mem_readSuccessorsOf complete (by apply Step_read.refCastFail (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption))
  case structNewDefault => exact structNewDefault_mem_completeReadSuccessorsOf complete (by apply Step_read.structNewDefault (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case structGetNull => exact structGetNull_mem_completeReadSuccessorsOf complete (by apply Step_read.structGetNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case structGetStruct => exact structGetStruct_mem_completeReadSuccessorsOf complete (by apply Step_read.structGetStruct (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayNewDefault => exact arrayNewDefault_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayNewDefault (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayNewElemOob => exact arrayNewElemOob_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayNewElemOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayNewElemAlloc => exact arrayNewElemAlloc_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayNewElemAlloc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayNewDataOob => exact arrayNewDataOob_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayNewDataOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayNewDataNum => exact arrayNewDataNum_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayNewDataNum (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayGetNull => exact arrayGetNull_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayGetNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayGetOob => exact arrayGetOob_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayGetOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayGetArray => exact arrayGetArray_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayGetArray (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayLenNull => exact arrayLenNull_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayLenNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayLenArray => exact arrayLenArray_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayLenArray (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayFillNull => exact arrayFillNull_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayFillNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayFillOob => exact arrayFillOob_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayFillOob (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayFillZero => exact arrayFillZero_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayFillZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayFillSucc => exact arrayFillSucc_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayFillSucc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayCopyNull1 => exact arrayCopyNull1_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayCopyNull1 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayCopyNull2 => exact arrayCopyNull2_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayCopyNull2 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayCopyOob1 => exact arrayCopyOob1_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayCopyOob1 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayCopyOob2 => exact arrayCopyOob2_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayCopyOob2 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayCopyZero => exact arrayCopyZero_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayCopyZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayCopyLe => exact arrayCopyLe_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayCopyLe (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayCopyGt => exact arrayCopyGt_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayCopyGt (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitElemNull => exact arrayInitElemNull_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitElemNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitElemOob1 => exact arrayInitElemOob1_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitElemOob1 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitElemOob2 => exact arrayInitElemOob2_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitElemOob2 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitElemZero => exact arrayInitElemZero_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitElemZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitElemSucc => exact arrayInitElemSucc_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitElemSucc (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitDataNull => exact arrayInitDataNull_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitDataNull (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitDataOob1 => exact arrayInitDataOob1_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitDataOob1 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitDataOob2 => exact arrayInitDataOob2_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitDataOob2 (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitDataZero => exact arrayInitDataZero_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitDataZero (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)
  case arrayInitDataNum => exact arrayInitDataNum_mem_completeReadSuccessorsOf complete (by apply Step_read.arrayInitDataNum (authority := amendedExecutionAuthority) (Nm := releasedNumerics) <;> assumption)

end WasmGemmGnaf.Wasm.Core.Exec
