//! `xtask sources root [--check]` -- root import module. Replaces `Tools/root.py`.
//!
//! SPEC section 5 fixes the layer structure. A file that belongs to no layer is
//! scratch, and scratch in the proof path is how a broken or unreviewed module
//! reaches the build.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::repo::{lean_files, slash};
use crate::spec::{Outcome, Result, SpecError};

const CLAUSE: &str = "5";

/// SPEC section 5 layer order. The generated file imports layers in this
/// sequence, so the root module reflects the dependency order the SPEC fixes.
const LAYERS: [&str; 10] = [
    "Foundation",
    "Wasm",
    "Cost",
    "Gemm",
    "GNAF",
    "Universal",
    "Atlas",
    "Artifact",
    "Theorems",
    "Conformance",
];

const ROOT_MODULE: &str = "WasmGemmGnaf.lean";

pub fn run(check: bool) -> Result<Outcome> {
    match report(check)? {
        Ok(clean) => {
            println!("{clean}");
            Ok(Outcome::Pass)
        }
        Err(stale) => {
            println!("{stale}");
            Ok(Outcome::Fail)
        }
    }
}

/// The root-module verdict as text. With `check` this only reports; without it
/// the file is regenerated.
pub fn report(check: bool) -> Result<std::result::Result<String, String>> {
    let mut modules: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    let mut unowned = Vec::new();

    for path in lean_files(CLAUSE, Path::new("WasmGemmGnaf"))? {
        let display = slash(&path);
        let rel = display
            .strip_prefix("WasmGemmGnaf/")
            .and_then(|r| r.strip_suffix(".lean"))
            .unwrap_or(&display);

        // A module belongs to a layer only if it sits INSIDE one of the SPEC 5
        // layer directories. A `.lean` file loose at the top of WasmGemmGnaf/
        // has no owning layer and is scratch.
        let layer = rel
            .split_once('/')
            .and_then(|(head, _)| LAYERS.iter().copied().find(|l| *l == head));

        match layer {
            Some(layer) => modules
                .entry(layer)
                .or_default()
                .push(format!("WasmGemmGnaf.{}", rel.replace('/', "."))),
            None => unowned.push(format!("WasmGemmGnaf/{rel}.lean")),
        }
    }

    if !unowned.is_empty() {
        let mut out = vec!["UNOWNED MODULES (belong to no SPEC 5 layer — scratch?):".to_string()];
        out.extend(unowned.iter().map(|u| format!("  {u}")));
        return Ok(Err(out.join("\n")));
    }

    let total: usize = modules.values().map(Vec::len).sum();
    let text = render(&modules);
    let path = PathBuf::from(ROOT_MODULE);

    if check {
        let current = if path.exists() {
            fs::read_to_string(&path)
                .map_err(|e| SpecError::io(CLAUSE, "cannot read", &path, e))?
        } else {
            String::new()
        };
        if current != text {
            return Ok(Err("WasmGemmGnaf.lean is STALE — run `just root`".to_string()));
        }
        Ok(Ok(format!("root imports current: {total} modules, no unowned files")))
    } else {
        fs::write(&path, &text)
            .map_err(|e| SpecError::io(CLAUSE, "cannot write", &path, e))?;
        Ok(Ok(format!("root regenerated: {total} modules")))
    }
}

fn render(modules: &BTreeMap<&str, Vec<String>>) -> String {
    let mut out = vec![
        "/-".to_string(),
        "  Root module: imports every layer of the WASM-GEMM-GNAF development.".to_string(),
        "  Generated by `just root`; do not edit by hand.".to_string(),
        "-/".to_string(),
        String::new(),
    ];
    for layer in LAYERS {
        if let Some(names) = modules.get(layer) {
            out.push(format!("-- {layer}"));
            let mut sorted = names.clone();
            sorted.sort();
            out.extend(sorted.into_iter().map(|m| format!("import {m}")));
            out.push(String::new());
        }
    }
    out.push("set_option autoImplicit false".to_string());
    format!("{}\n", out.join("\n").trim_end())
}
